// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {context} from '../models';

export function AddFiles(arg1:string,arg2:Array<string>):Promise<models.ArchiveResult>;

export function AddFolder(arg1:string,arg2:string):Promise<models.ArchiveResult>;

export function CancelOperation():Promise<void>;

export function CreateNewArchive(arg1:string,arg2:Array<string>):Promise<models.ArchiveResult>;

export function DeleteEntries(arg1:string,arg2:Array<string>):Promise<models.ArchiveResult>;

export function ExtractFiles(arg1:string,arg2:string,arg3:Array<string>):Promise<models.ArchiveResult>;

export function OpenArchive(arg1:string):Promise<Array<models.FileInfo>>;

export function SelectArchiveFile():Promise<string>;

export function SelectExtractFolder():Promise<string>;

export function SelectFilesToCompact():Promise<Array<string>>;

export function SelectFolderToCompact():Promise<string>;

export function SelectSaveFile():Promise<string>;

export function Startup(arg1:context.Context):Promise<void>;

export function TestArchive(arg1:string):Promise<models.ArchiveResult>;
