// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFiles(arg1, arg2) {
  return window['go']['services']['ArchiveService']['AddFiles'](arg1, arg2);
}

export function AddFolder(arg1, arg2) {
  return window['go']['services']['ArchiveService']['AddFolder'](arg1, arg2);
}

export function CancelOperation() {
  return window['go']['services']['ArchiveService']['CancelOperation']();
}

export function CreateNewArchive(arg1, arg2) {
  return window['go']['services']['ArchiveService']['CreateNewArchive'](arg1, arg2);
}

export function DeleteEntries(arg1, arg2) {
  return window['go']['services']['ArchiveService']['DeleteEntries'](arg1, arg2);
}

export function ExtractFiles(arg1, arg2, arg3) {
  return window['go']['services']['ArchiveService']['ExtractFiles'](arg1, arg2, arg3);
}

export function OpenArchive(arg1) {
  return window['go']['services']['ArchiveService']['OpenArchive'](arg1);
}

export function SelectArchiveFile() {
  return window['go']['services']['ArchiveService']['SelectArchiveFile']();
}

export function SelectExtractFolder() {
  return window['go']['services']['ArchiveService']['SelectExtractFolder']();
}

export function SelectFilesToCompact() {
  return window['go']['services']['ArchiveService']['SelectFilesToCompact']();
}

export function SelectFolderToCompact() {
  return window['go']['services']['ArchiveService']['SelectFolderToCompact']();
}

export function SelectSaveFile() {
  return window['go']['services']['ArchiveService']['SelectSaveFile']();
}

export function Startup(arg1) {
  return window['go']['services']['ArchiveService']['Startup'](arg1);
}

export function TestArchive(arg1) {
  return window['go']['services']['ArchiveService']['TestArchive'](arg1);
}
